package jp.gr.java_conf.SenseMusicClock



val SHAREDPREFERENCES_NAME  = R.string.SHAREDPREFERENCES_NAME
val MUSIC_DIR_RELATIVE_PATHS_KEY = R.string.MUSIC_DIR_RELATIVE_PATHS_KEY



val VOLUME_ADJUSTMENT = R.string.VOLUME_ADJUSTMENT

val ReLoad_Tracks_KEY = R.string.RELOAD_TRACKS_KEY